//
//  AddIngredientsConfigurator.swift
//  Nutrition Analysis
//
//  Created by azah on 6/25/21.
//  Copyright (c) azah mahgoub. All rights reserved.
//
//  This file was generated by the Xcode Templates so
//  you can apply clean architecture with MVVMC to your iOS and Mac projects.

import UIKit

class AddIngredientsCordinator {
    weak var navigationController: UINavigationController?
   
   init(navigationController: UINavigationController) {
       self.navigationController = navigationController
    }
    func start() {
        let viewModel = AddIngredientsViewModel.init(cordinator: self, useCaeProtocol: GetNutritionDataUseCase(), repoImpl: NutritionRepoImpl())
        let vc = AddIngredientsViewController.init(viewModel: viewModel)
        navigationController?.pushViewController(vc, animated: true)
    }

    func routToIngredientList(ingredientList: [AddIngredientsUIViewModel]) {
        IngredientListCordinator.init(navigationController: navigationController!).start(ingredinetList: ingredientList)
   }
}
